#!/usr/bin/env bash
python3 ./crawler.py '0-工業區名單/0-南投/10.南崗工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-南投/10.竹山工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台南/08安平工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台南/07-台南科技工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台南/06永康工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台南/05官田工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台中/甲幼廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台中/5.大里工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台中/4.台中工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-台中/3.台中港關連工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-屏東/14-屏東工業區廠商名錄(無).xlsx'
python3 ./crawler.py '0-工業區名單/0-屏東/15屏南工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-屏東/16-內埔工業區廠商名錄.xlsx'


python3 ./crawler.py '0-工業區名單/0-嘉義/03-義竹工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-嘉義/03-朴子工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-嘉義/02-嘉太工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-嘉義/01頭橋工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-嘉義/01民雄工業區廠商名錄.csv'
python3 ./crawler.py '0-工業區名單/0-彰化/6.全興工業區廠商名冊.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/7.彰濱工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/8.埤頭廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/8.田中廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/8.福興廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/9.社頭織襪園區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-彰化/9.芳苑工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/中壢.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/大園.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/平鎮.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/林口.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/桃幼.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/觀音.xlsx'
python3 ./crawler.py '0-工業區名單/0-桃園(含林口)/龜山工業區廠商名錄--106.05.31版.xlsx'
python3 ./crawler.py '0-工業區名單/0-苗栗/1.竹南工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-苗栗/1.銅鑼工業區廠商名錄 .xlsx'
python3 ./crawler.py '0-工業區名單/0-苗栗/1.頭份工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-雲林/11.斗六工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-雲林/12.雲林科技工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-雲林/13.豐田工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-雲林/14.雲林離島式基礎工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-雲林/元長工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/09-永安工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/10臨海工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/11(無)-鳳山工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/11大發工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/12-仁武工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/12-大社工業區廠商名錄.xlsx'
python3 ./crawler.py '0-工業區名單/0-高雄/13-1060612林園工業區廠商名錄.xlsx'

