#!/usr/bin/env bash
python ./crawler.py '0-工業區名單/0-南投/10.南崗工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-南投/10.竹山工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台南/08安平工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台南/07-台南科技工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台南/06永康工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台南/05官田工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台中/甲幼廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台中/5.大里工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台中/4.台中工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-台中/3.台中港關連工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-嘉義/03-義竹工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-嘉義/03-朴子工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-嘉義/02-嘉太工業區廠商名錄.xlsx'
python ./crawler.py '0-工業區名單/0-嘉義/01頭橋工業區廠商名錄.xlsx'